import 'package:flutter/material.dart';
import 'package:wathsapp/presentation/posteitems.dart';

class PostSection extends StatefulWidget {
  const PostSection({super.key});

  @override
  State<PostSection> createState() => _PostSectionState();
}

class _PostSectionState extends State<PostSection> {
  final List<Map> posts = [
    {
      "profile": "images/avatar/profile1.png",
      "post": "assets/videos/video1.mp4",
      "name": "Mamadou",
      "audio": "dip doundou guisse",
      "like": "100",
      "comment": "30",
      "partage": "12",
      "description": "garra qui fait un discours pour les femmes ou hommes mariés on aura tout vu 😂😂😂🤣🤣🤣 L'alliance en mode joie 🤣🤣🤣😂😂😍 ",
      "date": "il y a 12h",
      "sertifier": true,
      'comments': [
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
      ],
    },
    {
      "profile": "images/avatar/profile2.jpg",
      "post": "assets/videos/video2.mp4",
      "name": "Raion",
      "audio": "dip doundou guisse",
      "like": "200",
      "comment": "30",
      "partage": "15",
      "description": "sur blood striker je fume tout vos joueurs dans n'importe quel mode au sniper 😒😒😎😎🤴👊👊",
      "date": "il y a 1 jour",
      "sertifier": false,
      'comments': [
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
      ],
    },
    {
      "profile": "images/avatar/profile3.jpg",
      "post": "images/avatar/profile1.png",
      "name": "Senshi",
      "audio": "",
      "like": "300",
      "comment": "30",
      "partage": "20",
      "description": "bonjour aujourd’hui on n’a pas pu faire le live mais on se capte demain",
      "date": "il y a 2 jours",
      "sertifier": false,
      'comments': [
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
      ],
    },
    {
      "profile": "images/avatar/profile4.jpg",
      "post": "assets/videos/video3.mp4",
      "name": "Lamine",
      "audio": "Beat Street",
      "like": "150",
      "comment": "30",
      "partage": "10",
      "description": "elle croyait quoi en fait 😒😂🤣😎",
      "date": "il y a 3 min",
      "sertifier": true,
      'comments': [
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
        {'avatar': 'images/avatar/profile1.png', 'name': 'Leo', 'text': 'Trop stylé 😎'},
        {'avatar': 'images/avatar/profile2.jpg', 'name': 'Camille', 'text': 'Magnifique 😍'},
        {'avatar': 'images/avatar/profile3.jpg', 'name': 'Sam', 'text': 'Wow super! 🔥'},
        {'avatar': 'images/avatar/profile4.jpg', 'name': 'Emma', 'text': 'J’adore! ❤️'},
        {'avatar': 'images/avatar/profile5.jpg', 'name': 'Léa', 'text': 'Incroyable 😲'},
      ],
    },
  ];


  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      physics: const NeverScrollableScrollPhysics(),
      shrinkWrap: true,
      itemCount: posts.length,
      itemBuilder: (context, index) {
        return PostItem(item: posts[index]);
      },
    );
  }
}
